# Generated by Django 4.2.30 on 2026-07-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='إسم الجامعة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الجامعة')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إسم الوحدة/ الكيان')),
                ('code', models.CharField(max_length=20, verbose_name='رمز الوحدة')),
                ('unit_type', models.CharField(choices=[('FACULTY', 'كلية'), ('PRESIDENCY', 'رئاسة الجامعة'), ('LABORATORY', 'مخبر بحث'), ('INSTITUTE', 'معهد'), ('CENTER', 'مركز خدمة / مكتبة')], default='FACULTY', max_length=20, verbose_name='نوع الكيان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='organization.organizationalunit', verbose_name='الجهة التابع لها (إن وجدت)')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'وحدة تنظيمية',
                'verbose_name_plural': 'الوحدات التنظيمية',
                'unique_together': {('university', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم/الفرع')),
                ('code', models.CharField(max_length=20, verbose_name='رمز القسم')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organizationalunit', verbose_name='الوحدة التنظيمية')),
            ],
            options={
                'verbose_name': 'قسم / فرع',
                'verbose_name_plural': ' الاقسام و الفروع',
                'unique_together': {('unit', 'code')},
            },
        ),
    ]
