# Generated by Django 4.2.30 on 2026-08-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbslutNameUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الهيكل المعياري')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الوحدة')),
                ('unit_type', models.CharField(choices=[('FACULTY', 'كلية'), ('INSTITUTE', 'معهد'), ('VICE_PRESIDENCY', 'نيابة مديرية الجامعة'), ('DEANERY', 'العمادة'), ('VICE_DEANERY', 'نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('SERVICE', 'مصلحة'), ('LABORATORY', 'مخبر / مركز بحث'), ('LIBRARY', 'مكتبة'), ('OTHER', 'هيكل آخر')], max_length=30, verbose_name='نوع الهيكل')),
                ('default_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.abslutnameunit', verbose_name='التبعية المعيارية الافتراضية')),
            ],
            options={
                'verbose_name': 'مرجع هيكلي قياسي',
                'verbose_name_plural': 'المراجع الهيكلية القياسية',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم / الفرع')),
                ('code', models.CharField(max_length=20, verbose_name='رمز القسم')),
            ],
            options={
                'verbose_name': 'قسم أكاديمي',
                'verbose_name_plural': 'الأقسام الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الوحدة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_services', to='organization.department', verbose_name='القسم الأكاديمي التابعة له (إن وجد)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.abslutnameunit', verbose_name='نوع الهيكل المعياري')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='organization.organizationalunit', verbose_name='الجهة التابع لها إدارياً')),
            ],
            options={
                'verbose_name': 'وحدة تنظيمية',
                'verbose_name_plural': 'الوحدات التنظيمية',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='إسم الجامعة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الجامعة')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان المنصب')),
                ('legal_duties', models.TextField(blank=True, verbose_name='المهام بنص القانون')),
                ('office_hours', models.CharField(blank=True, max_length=200, verbose_name='مواعيد الاستقبال')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود البرمجي للمنصب')),
                ('occupant_type', models.CharField(choices=[('TEACHER', 'أستاذ'), ('STAFF', 'موظف إداري')], default='STAFF', max_length=15, verbose_name='طبيعة الشاغر للمنصب')),
                ('current_occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupying_positions', to=settings.AUTH_USER_MODEL, verbose_name='من يشغل المنصب حالياً')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.department', verbose_name='القسم الأكاديمي (إن وجد)')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organization.position', verbose_name='المنصب الأعلى مسؤوليّة')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.organizationalunit', verbose_name='الوحدة التنظيمية / المصلحة')),
            ],
            options={
                'verbose_name': 'منصب إداري / أكاديمي',
                'verbose_name_plural': 'المناصب الإدارية والأكاديمية',
            },
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.university', verbose_name='الجامعة'),
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organizationalunit', verbose_name='الكلية / المعهد التابع له'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationalunit',
            unique_together={('university', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('unit', 'code')},
        ),
    ]
