# Generated by Django 4.2.30 on 2026-07-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={},
        ),
    ]
