# Generated by Django 4.2.30 on 2026-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffprofile_department_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='department',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AlterField(
            model_name='abslutnameunit',
            name='unit_type',
            field=models.CharField(choices=[('FACULTY', 'كلية'), ('INSTITUTE', 'معهد'), ('VICE_PRESIDENCY', 'نيابة مديرية الجامعة'), ('DEANERY', 'العمادة'), ('VICE_DEANERY', 'نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('SERVICE', 'مصلحة'), ('LABORATORY', 'مخبر / مركز بحث'), ('LIBRARY', 'مكتبة'), ('DEPARTMENT', 'قسم'), ('OTHER', 'هيكل آخر')], max_length=30, verbose_name='نوع الهيكل'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
