# Generated by Django 4.2.30 on 2026-08-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organizationalunit_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbslutNameUnit',
            new_name='AbstractNameUnit',
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='organization.abstractnameunit', verbose_name='نوع الهيكل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم الفعلي للوحدة'),
        ),
    ]
