# Generated by Django 4.2.30 on 2026-08-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_alter_departement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'جامعة', 'verbose_name_plural': 'الجامعات'},
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.CharField(choices=[('FACULTY', 'كلية'), ('PRESIDENCY', 'رئاسة الجامعة'), ('LABORATORY', 'مخبر بحث'), ('INSTITUTE', 'معهد'), ('CENTER', 'مركز خدمة / مكتبة'), ('ADMIN_SERVICE', 'مصلحة إدارية / أمانة / عمادة')], default='FACULTY', max_length=20, verbose_name='نوع الكيان'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان المنصب')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود البرمجي للمنصب')),
                ('current_occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupying_positions', to=settings.AUTH_USER_MODEL, verbose_name='من يشغل المنصب حالياً')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.departement', verbose_name='القسم الأكاديمي (إن وجد)')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organization.position', verbose_name='المنصب المسؤول عنه مباشرة')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.organizationalunit', verbose_name='الوحدة التنظيمية / المصلحة')),
            ],
            options={
                'verbose_name': 'منصب إداري',
                'verbose_name_plural': 'المناصب الإدارية',
            },
        ),
    ]
