# Generated by Django 4.2.30 on 2026-08-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_abslutnameunit_abstractnameunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='standard_structure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='organization.abstractnameunit', verbose_name='النوع المعياري'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractnameunit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='رمز الوحدة'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='organization.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.university'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractnameunit',
            unique_together={('name', 'unit_type')},
        ),
    ]
