# Generated by Django 4.2.30 on 2026-08-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_teacherprofile_photo'),
        ('organization', '0003_alter_university_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
    ]
