# Generated by Django 4.2.30 on 2026-08-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organizationalunit_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abstractnameunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='abstractnameunit',
            name='default_parent',
        ),
        migrations.AlterUniqueTogether(
            name='organizationalunit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.CharField(choices=[('UNIVERSITY', 'جامعة / رئاسة الجامعة'), ('FACULTY', 'كلية / معهد'), ('DEANERY', 'عمادة / نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('DEPARTMENT', 'قسم أكاديمي'), ('SERVICE', 'مصلحة'), ('BRANCH', 'فرع'), ('LIBRARY', 'مكتبة')], default='', max_length=20, verbose_name='نوع الوحدة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='organization.organizationalunit', verbose_name='الوحدة الأعلى'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='standard_structure',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='university',
        ),
        migrations.DeleteModel(
            name='AbstractNameUnit',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
