# Generated by Django 4.2.30 on 2026-08-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_departement_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'قسم أكاديمي', 'verbose_name_plural': 'الأقسام الأكاديمية'},
        ),
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'verbose_name': 'وحدة تنظيمية', 'verbose_name_plural': 'الوحدات التنظيمية'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'منصب إداري / أكاديمي', 'verbose_name_plural': 'المناصب الإدارية والأكاديمية'},
        ),
        migrations.AddField(
            model_name='position',
            name='occupant_type',
            field=models.CharField(choices=[('TEACHER', 'أستاذ'), ('STAFF', 'موظف إداري')], default='STAFF', max_length=15, verbose_name='طبيعة الشاغر للمنصب'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القسم / الفرع'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organizationalunit', verbose_name='الكلية / المعهد التابع له'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(max_length=50, verbose_name='رمز الوحدة'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم الوحدة / الكيان'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='organization.organizationalunit', verbose_name='الجهة التابع لها إدارياً'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.CharField(choices=[('FACULTY', 'كلية'), ('PRESIDENCY', 'رئاسة الجامعة'), ('SECRETARIAT_GENERAL', 'أمانة عامة'), ('LIBRARY', 'مكتبة الكلية / الجامعة'), ('ADMIN_SERVICE', 'مصلحة إدارية'), ('LABORATORY', 'مخبر بحث'), ('CENTER', 'مركز خدمة / مركز حسابات')], default='FACULTY', max_length=30, verbose_name='نوع الكيان'),
        ),
        migrations.AlterField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organization.position', verbose_name='المنصب الأعلى مسؤوليّة'),
        ),
    ]
