# Generated by Django 4.2.30 on 2026-08-17 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_alter_abstractnameunit_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='مسمى المنصب')),
                ('code', models.SlugField(unique=True, verbose_name='رمز المنصب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف الوظيفي')),
            ],
            options={
                'verbose_name': 'نوع المنصب',
                'verbose_name_plural': 'أنواع المناصب',
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية التكليف')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية التكليف')),
                ('is_active', models.BooleanField(default=True, verbose_name='منصب حالي نشط')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.positiontype', verbose_name='نوع المنصب')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.organizationalunit', verbose_name='الوحدة التنظيمية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف / الأستاذ')),
            ],
            options={
                'verbose_name': 'تعيين في منصب',
                'verbose_name_plural': 'تعيينات المناصب',
            },
        ),
    ]
