# Generated by Django 4.2.30 on 2026-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organizationalunit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.CharField(choices=[('FACULTY', 'كلية'), ('INSTITUTE', 'معهد'), ('VICE_PRESIDENCY', 'نيابة مديرية الجامعة'), ('DEANERY', 'عمادة الكلية'), ('VICE_DEANERY', 'نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('SERVICE', 'مصلحة'), ('LABORATORY', 'مخبر / مركز بحث'), ('LIBRARY', 'مكتبة'), ('OTHER', 'هيكل آخر')], max_length=30, verbose_name='نوع الهيكل'),
        ),
    ]
