# Generated by Django 4.2.30 on 2026-08-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_positiontype_positionassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={},
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='code',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تسمية خاصة إن وجدت'),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'unit_type': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationalunit'),
        ),
        migrations.CreateModel(
            name='OrganizationalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الوحدة النمطي')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز الموحد')),
                ('unit_type', models.CharField(choices=[('UNIVERSITY', 'جامعة / رئاسة الجامعة'), ('FACULTY', 'كلية / معهد'), ('DEANERY', 'عمادة / نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('DEPARTMENT', 'قسم أكاديمي'), ('SERVICE', 'مصلحة'), ('BRANCH', 'فرع'), ('LIBRARY', 'مكتبة')], max_length=20)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationaltemplate')),
            ],
            options={
                'verbose_name': 'نموذج هيكلي قانوني',
            },
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='organization.organizationaltemplate', verbose_name='النموذج الهيكلي القانوني'),
            preserve_default=False,
        ),
    ]
