# Generated by Django 4.2.30 on 2026-08-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organizationalunit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_services', to='organization.department', verbose_name='القسم الأكاديمي التابعة له (إن وجد)'),
        ),
    ]
