# Generated by Django 4.2.30 on 2026-08-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organizationalunit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'verbose_name': 'وحدة تنظيمية', 'verbose_name_plural': 'الوحدات التنظيمية'},
        ),
    ]
