# Generated by Django 4.2.30 on 2026-08-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organizationalunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationaltemplate',
            options={'verbose_name': 'نموذج هيكلي قانوني', 'verbose_name_plural': 'نماذج هيكلية قانونية'},
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationalunit', verbose_name='الوحدة المباشرة الأعلى'),
        ),
        migrations.AlterField(
            model_name='organizationaltemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationaltemplate', verbose_name='الوحدة النمطية الأعلى'),
        ),
        migrations.AlterField(
            model_name='organizationaltemplate',
            name='unit_type',
            field=models.CharField(choices=[('UNIVERSITY', 'جامعة / رئاسة الجامعة'), ('FACULTY', 'كلية / معهد'), ('DEANERY', 'عمادة / نيابة عمادة'), ('SECRETARIAT', 'أمانة عامة'), ('DEPARTMENT', 'قسم أكاديمي'), ('SERVICE', 'مصلحة'), ('BRANCH', 'فرع'), ('LIBRARY', 'مكتبة')], max_length=20, verbose_name='نوع الوحدة'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_units', to='organization.organizationalunit', verbose_name='الكلية / المعهد'),
        ),
    ]
