# Generated by Django 4.2.30 on 2026-08-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organizationaltemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='custom_name',
        ),
    ]
