# Generated by Django 4.2.30 on 2026-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_remove_organizationalunit_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم المخصص (مثل اسم الكلية/القسم)'),
        ),
    ]
