# Generated by Django 4.2.30 on 2026-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationalunit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الكلية / الكيان'),
        ),
    ]
