# Generated by Django 4.2.30 on 2026-08-16 14:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin'), ('STAFF', 'Staff')], max_length=50, verbose_name='نوع الحساب')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('num_inscription', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='رقم التسجيل')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ar', models.CharField(max_length=50, verbose_name='الاسم بالعربية')),
                ('last_name_ar', models.CharField(max_length=50, verbose_name='اللقب بالعربية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(max_length=100, verbose_name='مكان الميلاد')),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teachers/photos/', verbose_name='الصورة الشخصية')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي / المعرف')),
                ('rank', models.CharField(max_length=50, verbose_name='الرتبة الأكاديمية')),
                ('grade', models.CharField(max_length=50, verbose_name='الدرجة')),
                ('joining_date', models.DateField(verbose_name='تاريخ أول الالتحاق')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التثبيت')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('office_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم/موقع المكتب')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة مختصرة')),
            ],
        ),
    ]
