# Generated by Django 4.2.30 on 2026-07-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
