# Generated by Django 4.2.30 on 2026-07-29 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_departement_options_and_more'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ar', models.CharField(max_length=50, verbose_name='الاسم بالعربية')),
                ('last_name_ar', models.CharField(max_length=50, verbose_name='اللقب بالعربية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(max_length=100, verbose_name='مكان الميلاد')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='الصورة الشخصية')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي / المعرف')),
                ('rank', models.CharField(max_length=50, verbose_name='الرتبة الأكاديمية')),
                ('grade', models.CharField(max_length=20, verbose_name='الدرجة')),
                ('joining_date', models.DateField(verbose_name='تاريخ أول الالتحاق')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التثبيت')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('office_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم/موقع المكتب')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة مختصرة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organization.departement', verbose_name='القسم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف أستاذ',
                'verbose_name_plural': 'ملفات الأساتذة',
            },
        ),
    ]
