# Generated by Django 4.2.30 on 2026-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='num_inscription',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, unique=True, verbose_name='رقم التسجيل'),
        ),
    ]
