# Generated by Django 4.2.30 on 2026-08-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='teachers/cvs/', verbose_name='السيرة الذاتية (PDF)'),
        ),
    ]
