# Generated by Django 4.2.30 on 2026-08-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('accounts', '0004_teacherprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='organization.organizationalunit', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'AbslutNameUnit': 'قسم'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organization.organizationalunit', verbose_name='القسم'),
        ),
    ]
