# Generated by Django 4.2.30 on 2026-08-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_abslutnameunit_abstractnameunit_and_more'),
        ('accounts', '0005_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'AbstractNameUnit': 'قسم'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organization.organizationalunit', verbose_name='القسم'),
        ),
    ]
