# Generated by Django 4.2.30 on 2026-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacherprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
    ]
