# Generated by Django 4.2.30 on 2026-08-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin'), ('STAFF', 'Staff')], default=2, max_length=20, verbose_name='نوع الحساب'),
            preserve_default=False,
        ),
    ]
