# Generated by Django 4.2.30 on 2026-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_role_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin'), ('STAFF', 'Staff')], default='STUDENT', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
