# Generated by Django 4.2.30 on 2026-08-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserType',
            new_name='user_type',
        ),
    ]
