# Generated by Django 4.2.30 on 2026-08-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_usertype_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade',
            field=models.CharField(max_length=50, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin'), ('STAFF', 'Staff')], max_length=50, verbose_name='نوع الحساب'),
        ),
    ]
