# Generated by Django 4.2.30 on 2026-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_teacherprofile_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teachers/photos/', verbose_name='الصورة الشخصية'),
        ),
    ]
