# Generated by Django 4.2.30 on 2026-08-16 14:29

import Academic_Mobility.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMobilityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('file1', models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_admin_file_path)),
                ('file2', models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_scientific_file_path)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='إضافة ملاحظة')),
                ('final_report', models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_report_file_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_updated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=12, verbose_name='حالة الطلب')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض (في حال الرفض)')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
