# Generated by Django 4.2.30 on 2026-08-12 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMobilityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='قيد المعالجة', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('file1', models.FileField(blank=True, upload_to='uploadstage')),
                ('file2', models.FileField(blank=True, upload_to='uploadstage')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='إضافة ملاحظة')),
                ('notes1', models.CharField(blank=True, max_length=255, null=True, verbose_name='إضافة ملاحظة')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
