# Generated by Django 4.2.30 on 2026-08-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Mobility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicmobilityorder',
            name='notes1',
        ),
    ]
