# Generated by Django 4.2.30 on 2026-08-12 18:54

import Academic_Mobility.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Mobility', '0002_remove_academicmobilityorder_notes1'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmobilityorder',
            name='final_report',
            field=models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_report_file_path),
        ),
        migrations.AlterField(
            model_name='academicmobilityorder',
            name='file1',
            field=models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_admin_file_path),
        ),
        migrations.AlterField(
            model_name='academicmobilityorder',
            name='file2',
            field=models.FileField(blank=True, upload_to=Academic_Mobility.upload_paths.mobility_scientific_file_path),
        ),
    ]
