# Generated by Django 4.2.30 on 2026-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Mobility', '0003_academicmobilityorder_final_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmobilityorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض (في حال الرفض)'),
        ),
    ]
