# Generated by Django 4.2.30 on 2026-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Mobility', '0004_academicmobilityorder_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicmobilityorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=12, verbose_name='حالة الطلب'),
        ),
    ]
